@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package mrp_v2.versatileportals.block.util;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;