@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package mrp_v2.customteleporters.client.renderer.color;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;