@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package mrp_v2.randomdimensions.common.capabilities;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;