@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package mrp_v2.versatileportals.common.capabilities;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;