@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package mrp_v2.versatileportals.client.util;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;