@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package mrp_v2.versatileportals.config;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;