@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package mrp_v2.versatileportals.datagen;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;