@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package mrp_v2.customteleporters.particles;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;