@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package mrp_v2.customteleporters.tileentity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;