@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package mrp_v2.versatileportals.client.particle;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;