@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package mrp_v2.randomdimensions.client.particle;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;