@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package mrp_v2.versatileportals.particles;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;