@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package mrp_v2.customteleporters.client.particle;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;