@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package mrp_v2.randomdimensions.particles;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;