@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package mrp_v2.versatileportals.tileentity.util;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;