@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package mrp_v2.customteleporters.common.capabilities;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;